name: 🐞 Bug Report
description: Report a bug or issue with a database toolbox image
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue with the MCP Database Toolbox!
        
        Before submitting, please:
        - Check existing issues to avoid duplicates
        - Review the README for common issues
        - Ensure you're using the latest image version
        
        Please fill in as much information as possible to help us diagnose the problem.
  - type: dropdown
    attributes:
      label: Which database toolbox is affected?
      description: Select the database image experiencing the issue
      options:
        - AlloyDB for PostgreSQL
        - BigQuery
        - Bigtable
        - Cloud SQL (MySQL)
        - Cloud SQL (PostgreSQL)
        - Cloud SQL (SQL Server)
        - Couchbase
        - Dataplex
        - Dgraph
        - Firestore
        - Looker
        - MongoDB
        - MySQL
        - Neo4j
        - PostgreSQL
        - Redis
        - Redshift
        - Spanner
        - SQL Server
        - SQLite
        - TiDB
        - Valkey
        - Multiple databases
        - Not database-specific
    validations:
      required: true
  
  - type: input
    attributes:
      label: Image Version/Tag
      description: Which version of the image are you using?
      placeholder: "e.g., v1.2.3, latest, sha-abc123"
    validations:
      required: true
  
  - type: dropdown
    attributes:
      label: Architecture
      description: What architecture are you running on?
      options:
        - linux/amd64
        - linux/arm64
        - Unknown
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Environment Details
      description: Provide information about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 14.0, Windows 11]
        - Docker Version: [e.g., 24.0.5]
        - Container Runtime: [e.g., Docker Desktop, Podman, containerd]
        - MCP Client: [e.g., Claude Desktop, custom client]
      value: |
        - OS: 
        - Docker Version: 
        - Container Runtime: 
        - MCP Client: 
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Docker Command / Configuration
      description: Share your docker run command or docker-compose.yml (redact sensitive credentials)
      placeholder: |
        docker run --rm -i \
          --name mcp-postgres \
          -e DATABASE_HOST=localhost \
          -e DATABASE_PORT=5432 \
          ghcr.io/usacognition/postgres-toolbox:latest \
          --prebuilt postgres \
          --stdio
      render: bash
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the bug
      placeholder: |
        1. Start the container with command X
        2. Connect using MCP client Y
        3. Execute query Z
        4. Observe error
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The image should connect successfully and execute queries
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages, stack traces, or logs
      placeholder: |
        Error: Connection refused
        Stack trace: ...
      render: shell
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Logs
      description: Paste relevant container logs (use `docker logs container-name`)
      render: shell
  
  - type: checkboxes
    attributes:
      label: Issue Type
      description: What type of issue is this? (Check all that apply)
      options:
        - label: Connection issue (cannot connect to database)
        - label: Authentication/credential issue
        - label: Query execution error
        - label: MCP protocol issue (--stdio mode)
        - label: Performance issue
        - label: Image build/startup failure
        - label: Environment variable not working
        - label: Multi-architecture issue
        - label: Documentation gap
  
  - type: textarea
    attributes:
      label: Additional Context
      description: Any other relevant information, workarounds you've tried, or related issues