name: "🚀 Feature Request"
description: Suggest a new feature or enhancement for the database toolbox
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement to the MCP Database Toolbox!
        
        We welcome ideas for:
        - New database support
        - Enhanced functionality for existing databases
        - Performance improvements
        - Security enhancements
        - Documentation improvements
        
        Please provide as much detail as possible.
  - type: dropdown
    attributes:
      label: Feature Category
      description: What type of feature are you requesting?
      options:
        - New database support
        - Enhancement to existing database
        - Performance improvement
        - Security enhancement
        - New MCP capabilities
        - Documentation improvement
        - CI/CD or infrastructure
        - Developer experience
        - Other
    validations:
      required: true
  
  - type: dropdown
    attributes:
      label: Which database(s) does this affect?
      description: Select the database(s) this feature relates to
      options:
        - AlloyDB for PostgreSQL
        - BigQuery
        - Bigtable
        - Cloud SQL (MySQL)
        - Cloud SQL (PostgreSQL)
        - Cloud SQL (SQL Server)
        - Couchbase
        - Dataplex
        - Dgraph
        - Firestore
        - Looker
        - MongoDB
        - MySQL
        - Neo4j
        - PostgreSQL
        - Redis
        - Redshift
        - Spanner
        - SQL Server
        - SQLite
        - TiDB
        - Valkey
        - New database (not yet supported)
        - All databases
        - Not database-specific
    validations:
      required: true
  
  - type: dropdown
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical - blocking my adoption
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: |
        Currently, I cannot... because...
        This makes it difficult to...
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see. Be as specific as possible.
      placeholder: |
        I would like the ability to...
        This could work by...
        Example usage:
        ```bash
        docker run ... --new-flag value
        ```
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Use Case / Example
      description: Provide a concrete example of how you would use this feature
      placeholder: |
        I want to connect to a Cassandra database from my MCP client.
        
        Example configuration:
        ```yaml
        database:
          type: cassandra
          hosts: ["node1", "node2"]
          keyspace: my_keyspace
        ```
  
  - type: textarea
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: |
        - I tried using X, but it doesn't support Y
        - I could manually do Z, but that's not scalable
  
  - type: checkboxes
    attributes:
      label: Additional Requirements
      description: Are there specific requirements for this feature?
      options:
        - label: Must support both amd64 and arm64 architectures
        - label: Must work with MCP --stdio mode
        - label: Must support environment variable configuration
        - label: Must include documentation and examples
        - label: Should have automated tests
        - label: Must maintain backward compatibility
  
  - type: checkboxes
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'd be willing to submit a PR for this feature
        - label: I'd be willing to help test this feature
        - label: I'd be willing to help with documentation
  
  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references that would help